// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cloud_logic': 'enable',
    'aws_cloud_logic_custom': [{
        "id": "tphwa6b4f6",
        "name": "Pets",
        "description": "",
        "endpoint": "https://tphwa6b4f6.execute-api.us-west-2.amazonaws.com/Development",
        "region": "us-west-2",
        "paths": ["/items", "/items/123"]
    }],
    'aws_cognito_identity_pool_id': 'us-west-2:a3d77028-40c9-4710-878d-5982140b018f',
    'aws_cognito_region': 'us-west-2',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'millenuum-hosting-mobilehub-644879776',
    'aws_content_delivery_bucket_region': 'us-west-2',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd24onx11lomg9o.cloudfront.net',
    'aws_dynamodb': 'enable',
    'aws_dynamodb_all_tables_region': 'us-west-2',
    'aws_dynamodb_table_schemas': [{
        "tableName": "millenuum-mobilehub-644879776-pets",
        "attributes": [{"name": "userId", "type": "S"}, {"name": "petId", "type": "S"}],
        "indexes": [],
        "region": "us-west-2",
        "hashKey": "userId",
        "rangeKey": "petId"
    }],
    'aws_mobile_analytics_app_id': '1e0b3afbe0b343a481deb6311f5be1f4',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': 'db0fed8d-2db3-11e8-8692-f56c6f73a3e3',
    'aws_project_name': 'Millenuum',
    'aws_project_region': 'us-west-2',
    'aws_resource_bucket_name': 'millenuum-deployments-mobilehub-644879776',
    'aws_resource_name_prefix': 'millenuum-mobilehub-644879776',
    'aws_sign_in_enabled': 'enable',
    'aws_user_files': 'enable',
    'aws_user_files_s3_bucket': 'millenuum-userfiles-mobilehub-644879776',
    'aws_user_files_s3_bucket_region': 'us-west-2',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-west-2_TZr0SBhmH',
    'aws_user_pools_mfa_type': 'ON',
    'aws_user_pools_web_client_id': '5b94l24602n1mubfd4n278i32',
    'aws_user_settings': 'enable',
}

export default awsmobile;
